`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 11/06/2025 02:19:04 AM
// Design Name: 
// Module Name: FP_Multiplier
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

// Generated By GPT


// =====================
// TOP MODULE (3x3 SYSTOLIC ARRAY)
// =====================
module top (
    input wire clk,
    // Matrix A
    input wire [7:0] arr_A0_0, arr_A0_1, arr_A0_2,
    input wire [7:0] arr_A1_0, arr_A1_1, arr_A1_2,
    input wire [7:0] arr_A2_0, arr_A2_1, arr_A2_2,
    // Matrix B
    input wire [7:0] arr_B0_0, arr_B0_1, arr_B0_2,
    input wire [7:0] arr_B1_0, arr_B1_1, arr_B1_2,
    input wire [7:0] arr_B2_0, arr_B2_1, arr_B2_2,
    // Matrix C
    output wire [7:0] arr_C0_0, arr_C0_1, arr_C0_2,
    output wire [7:0] arr_C1_0, arr_C1_1, arr_C1_2,
    output wire [7:0] arr_C2_0, arr_C2_1, arr_C2_2
);

    // Internal interconnect wires (manually flattened)
    wire [7:0] a_00_1, a_01_2, a_10_1, a_11_2, a_20_1, a_21_2;
    wire [7:0] b_00_1, b_10_1, b_20_1, b_01_2, b_11_2, b_21_2;

    // Row 0
    MAC mac00 (.clk(clk),
               .a_in(arr_A0_0), .b_in(arr_B0_0),
               .a_out(a_00_1), .b_out(b_00_1), .c_out(arr_C0_0));

    MAC mac01 (.clk(clk),
               .a_in(a_00_1), .b_in(arr_B0_1),
               .a_out(a_01_2), .b_out(b_01_2), .c_out(arr_C0_1));

    MAC mac02 (.clk(clk),
               .a_in(a_01_2), .b_in(arr_B0_2),
               .a_out(), .b_out(), .c_out(arr_C0_2));

    // Row 1
    MAC mac10 (.clk(clk),
               .a_in(arr_A1_0), .b_in(b_00_1),
               .a_out(a_10_1), .b_out(b_10_1), .c_out(arr_C1_0));

    MAC mac11 (.clk(clk),
               .a_in(a_10_1), .b_in(b_01_2),
               .a_out(a_11_2), .b_out(b_11_2), .c_out(arr_C1_1));

    MAC mac12 (.clk(clk),
               .a_in(a_11_2), .b_in(arr_B1_2),
               .a_out(), .b_out(), .c_out(arr_C1_2));

    // Row 2
    MAC mac20 (.clk(clk),
               .a_in(arr_A2_0), .b_in(b_10_1),
               .a_out(a_20_1), .b_out(b_20_1), .c_out(arr_C2_0));

    MAC mac21 (.clk(clk),
               .a_in(a_20_1), .b_in(b_11_2),
               .a_out(a_21_2), .b_out(b_21_2), .c_out(arr_C2_1));

    MAC mac22 (.clk(clk),
               .a_in(a_21_2), .b_in(arr_B2_2),
               .a_out(), .b_out(), .c_out(arr_C2_2));

endmodule
